version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=changethissecretkey
      - BACKEND_CORS_ORIGINS=["http://localhost:8000", "http://localhost:3000"]
    volumes:
      - ./app:/app/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: 